#!/bin/bash
while read line
do
    ipv6network=`echo $line|awk '{print $1}'`
    echo "ipv6network: $ipv6network"
    route -A inet6 del $ipv6network/64
done < del_route_table
/etc/init.d/quagga start
